my_street_analytics:
  target: dev
  outputs:
    dev:
      dataset: "{{ env_var('GCP_BQ_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /keys/gcp_key.json
      location: "{{ env_var('GCP_REGION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT') }}"
      threads: 1
      type: bigquery
    prod:
      dataset: "{{ env_var('GCP_BQ_DATASET') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /keys/gcp_key.json
      location: "{{ env_var('GCP_REGION') }}"
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT') }}"
      threads: 1
      type: bigquery