version: 2

sources:
  - name: staging
    database: hybrid-saga-412112
    schema: my_street_analytics
    tables:
      - name: external_street_events

models:
  - name: stg_street_events
    description: "staging table for all events. Serving as Data Lake."
    columns:
      - name: event_date
        data_type: date
        description: "when the event was registered"

      - name: event_category
        data_type: string
        description: "Category of the event"

      - name: event_type
        data_type: string
        description: "Type of the event"

      - name: municipal_parish
        data_type: string
        description: "Which Municipal Parish the event took place"

      - name: municipal_subsection_code
        data_type: int64
        description: "Code of subsection within Municipal Parish"

      - name: lon_subsection
        data_type: float64
        description: "Longitude for Municipal Parish Subsection"
      
      - name: lat_subsection
        data_type: float64
        description: "Latitute for Municipal Parish Subsection"



